pizzaria2/pizzaria/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('pizzas.urls', namespace='pizzas')),
]

pizzaria2/pizzas/urls.py
"""
Author: Brandon Rose
Date: 03-09-18
Class: ICT 4370
Assignment#: 9
Description: Django URL pattern matching 
"""

from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    #homepage
    path('', views.index, name='index'),
    #pizza types
    path(r'pizzas/', views.pizzas, name='pizzas'),
    #topppings per pizza
    path(r'pizza/<int:pizza_id>/', views.pizza, name='pizza'),
    #order page
    path(r'orders/', views.orders, name='orders'),
    #order summary
    path(r'order_summary/', views.order_summary, name='order_summary')
]

pizzaria2/users/urls.py
"""
Author: Brandon Rose
Date: 03-09-18
Class: ICT 4370
Assignment#: 9
Description: Django URL patterns for login, logout and user registration. 
"""

from django.urls import path
from django.contrib.auth.views import login 

from . import views

app_name='users'

urlpatterns = [
    # Login Page
    path(r'login/', login, {'template_name': 'users/login.html'}, name='login'),
    # Registration Page
    path(r'register/', views.register, name='register'),
    # Logout Page
    path(r'logout/', views.logout_view, name='logout'),
]

pizzaria2/pizzas/models.py
"""
Author: Brandon Rose
Date: 03-09-18
Class: ICT 4370
Assignment#: 9
Description: Django data model and DB mappings
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping = models.CharField(max_length=30)
    def __str__(self):
        return self.topping

class Post(models.Model):
    selection = models.CharField(max_length=30, default='test')
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.selection

class PizzaSize(models.Model):
    sizes = models.IntegerField(max_length=10)
    def __str__(self):
        return self.sizes

class CrustType(models.Model):
    crust = models.IntegerField(max_length=15)
    def __str__(self):
        return self.crust

pizzaria2/users/models.py
from django.db import models

# Create your models here.

pizzaria2/pizzas/forms.py
"""
Author: Brandon Rose
Date: 03-09-18
Class: ICT 4370
Assignment#: 10
Description: Django form for user pizza order
"""

from django import forms
from pizzas.models import Topping, Post, PizzaSize, CrustType
#from pizzas.models import Post


class OrderForm(forms.ModelForm):
    #toppings = []
    toppings = [(topping.id, str(topping)) for topping in Topping.objects.all()]
    sizes = [(size.id, str(size)) for size in PizzaSize.objects.all()]
    crusts = [(crust.id, str(crust)) for crust in CrustType.objects.all()]
    #toppings = (('Pepperoni', 'Blah'), ('Olives', 'Olives'),)
    selection = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices = toppings)
    size = forms.MultipleChoiceField(widget=forms.RadioSelect, choices = sizes)
    crust = forms.MultipleChoiceField(widget=forms.RadioSelect, choices = crusts)

    class Meta:
        model = Post
        exclude = ('', )     

pizzaria2/users/forms.py
"""
Author: Brandon Rose
Date: 03-09-18
Class: ICT 4370
Assignment#: 9
Description: Django form for user registration
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .pass_validator import validate_pass

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    phone = forms.CharField(max_length=11, required=True, help_text='Required.')
    address = forms.CharField(max_length=50, required=True, help_text='Required.')
    address2 = forms.CharField(max_length=50, required=False, help_text='Optional.')
    town = forms.CharField(max_length=11, required=True, help_text='Required.')
    zip = forms.CharField(max_length=5, required=True, help_text='Required.')
    state = forms.CharField(max_length=11, required=True, help_text='Required.')
    password1 = forms.CharField(validators=[validate_pass])

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'phone', 'address', 'address2', 'town', 'zip', 'state', 'password1', 'password2', )

pizzaria2/pizzas/views.py
"""
Author: Brandon Rosed
Date: 03-09-18
Class: ICT 4370
Assignment#: 9
Description: Django web page views and html docs
"""

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate

from .models import Pizza, Post, Topping, CrustType, PizzaSize
from django.contrib.auth.decorators import login_required
from pizzas.forms import OrderForm

# Create your views here.

def index(request):
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Show available pizzas"""
    pizzas = Pizza.objects.order_by('name')
    context = {'pizzas':pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Show toppings associated with a pizza"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()
    context = { 'pizza':pizza, 'toppings':toppings }
    return render(request, 'pizzas/toppings.html', context) 

@login_required
def orders(request):
    "Allow user to order if they are logged in"
    selections = Post.objects.all()
    crusts = CrustType.objects.all()
    sizes = PizzaSize.objects.get(id=1)
    if request.method != 'POST':
        # Display blank registration form
        form = OrderForm()
    else:
        # Process completed form
        form = OrderForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()


            return redirect('pizzas:orders')
    context = { 'form': form, 'selections': selections, 'crusts': crusts, 'sizes': sizes }
    return render(request, 'pizzas/orders.html', context)


def order_summary(request):
    selected_items = Post.objects.all()
    form = OrderForm()
    context = {'form': form, 'selected_items': selected_items }
    return render(request, 'pizzas/orders.html', context)

pizzaria2/users/views.py
"""
Author: Brandon Rose
Date: 03-09-18
Class: ICT 4370
Assignment#: 9
Description: Django web page view configuration.
"""

from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from users.forms import SignUpForm


def logout_view(request):
    """Log the user out"""
    logout(request)
    return HttpResponseRedirect(reverse('pizzas:index'))

def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display blank registration form
        form = SignUpForm()
    else:
        # Process completed form
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            #form.save()
            # Log the user in and redirect to home page
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('pizzas:index'))
    context = { 'form': form }
    return render(request, 'pizzas/register.html', context)

pizzaria2/pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">B's Pizzaria!!</a> - 
  <a href="{% url 'pizzas:pizzas' %}">The Pizzas</a> -
  <a href="{% url 'pizzas:orders' %}">Place Order</a> - 
  {%if user.is_authenticated %}
    Hello, {{ user.username }}.
    <a href="{% url 'users:logout' %}">log out</a>
  {% else %}
    <a href="{% url 'users:register' %}">register</a> - 
    <a href="{% url 'users:login' %}">log in</a>
  {% endif %}
</p>

{% block content %}{% endblock content %}

pizzaria2/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>View various pizzas and their toppings.</p>
{% endblock content %}

pizzaria2/pizzas/templates/pizzas/order_summary.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Order Summary</p>

    <p>Pizza Size: </p>

    <p>Toppings:</p>
  <ul>
  {% for selection in selections %}
    <li>
      <p>{{ selection }}</p>
    </li>
  {% empty %}
    <li>
      There are no toppings to display.
    </li>
  {% endfor %}
  </ul>




{% endblock content %}

pizzaria2/pizzas/templates/pizzas/orders.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Place an Order</p>

  <form method="post" action="{% url 'pizzas:orders' %}">
    {{ form.as_p }}
    {% csrf_token %}
   <button name="submit">Submit Order</button>

   <input type="hidden" name="next" value="{% url 'pizzas:order_summary' %}"/>
  </form>



      <p>{{ get_sizes_display }}<p>


 

  {% for crust in crusts %}

    <p>{{ crust }}<p>

  {% endfor %}

  {% for selection in selections %}

    <p>{{ selection }}<p>

  {% endfor %}

{% endblock content %}

pizzaria2/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Pizzas Available</p>

  <ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
      </li>
    {% empty %}
      <li>There are no Pizzas available yet. Sorry.</li>
    {% endfor %}
  </ul>

{% endblock content %}

pizzaria2/pizzas/templates/pizzas/register.html
{% extends "pizzas/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {{ form.as_p }}
    {% csrf_token %}
   <button name="submit">register</button>
   <input type="hidden" name="next" value="{% url 'pizzas:index' %}" />
  </form>

{% endblock content %}

pizzaria2/pizzas/templates/pizzas/toppings.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Pizza: {{ pizza }}</p>
 
  <p>Toppings:</p>
  <ul>
  {% for topping in toppings %}
    <li>
      <p>{{ topping }}</p>
    </li>
  {% empty %}
    <li>
      There are no toppings to display.
    </li>
  {% endfor %}
  </ul>

{% endblock content %}

pizzaria2/users/templates/users/login.html
{% extends "pizzas/base.html" %}

{% block content %}

  {% if form.errors %}
    <p>Your username abd password didn't match. Please try again.</p>
  {% endif %}

<form method="post" action="{% url 'users:login' %}">
  {% csrf_token %}
  {{ form.as_p }}

  <button name="submit">log in</button>
  <input type="hidden" name="next" value="{% url 'pizzas:index' %} />
</form>

{% endblock content %}